### ISSUE TITLE
Socket Error: couldn't connect to socket: -138.

### ISSUE THREAD

**Issue by tcoopman** [flackr/circ#158]
When try to connect to irc.freenode.net with:

```
/server irc.freenode.net
```

I get: 

```
Socket Error: couldn't connect to socket: -138.
```

This line keeps repeating many times. Other servers fail too with the same error.

I'm using chrome canary on windows 7 64bit.

**Comment by koutoftimer** [comment]
Don't want to close firewall. I'm trying to add the firewall exception for win 7. Who knows how to do that for CIRC?
