### ISSUE TITLE
Cannot connect multiple times to the same server

### ISSUE THREAD

**Issue by Vash63** [flackr/circ#276]
I run my own ZNC server locally, and per ZNC syntax you should log in with 'user/network' and the password. This seems to work in CIRC with "/server address:port user/network:password", however when I go to make my second connection using the same address and port with the alternate username to connect to my second network, nothing happens. No error or anything. 

I can connect to my networks in any order and this is 100% repeatable. Regardless of which network I connect to, it passes along the user/network/pass correctly and logs me into the right network on ZNC, but then I cannot add a second network.

**Comment by toddpratt** [comment]
I also need to connect to the same server twice.  Server data needs to be optionally keyed by a user-specified name / server alias rather than the actual hostname.

**Comment by snook** [comment]
Duplicate of #163

**Comment by Moter8** [comment]
:+1: Unusable combined with ZNC :(

**Comment by Vash63** [comment]
Indeed it is a dup if #163, I'll go ahead and close this one.
