### ISSUE TITLE
Detach this fork

### ISSUE THREAD

**Issue by mc10** [flackr/circ#319]
Since this repo has become independent of its parent, maybe it should be [detached from the parent](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile#commit-was-made-in-a-fork)? I think just leaving a link in the README pointing back to the parent repo would be sufficient.

**Comment by indrora** [comment]
(FWIW, this takes about 5 minutes to do with GitHub -- they're nice people!)

**Comment by flackr** [comment]
Done.
