### ISSUE TITLE
Cannot connect to same host with a different port

### ISSUE THREAD

**Issue by rahul0705** [flackr/circ#329]
If I try to connect to irc.example.com with port 7000 and then make a connection to irc.example.com with port 6777 it won't do anything

**Comment by BrandonG777** [comment]
Same here but I would like to make multiple connections to the same server on the same port but supplying different usernames and passwords.

**Comment by snook** [comment]
Duplicate of https://github.com/flackr/circ/issues/276

**Comment by rahul0705** [comment]
Any idea when #276 or any of the other issues will be fixed?
