### ISSUE TITLE
Could not find any version that matches com.android.support:support-v4:+

### ISSUE THREAD

**Issue by Honry** [flackr/circ#342]
Reproduce Steps
============================
1. clone circ
2. create circ project with cca
    $ cca create CIRC –link-to circ/package
3. build and run circ
    $ cd CIRC & cca run android

Error Log:
============================
lei@lei-Studio-XPS-8000:~/work/workspace/cordova/cordova-4.0/google_plugins/CIRC$ cca run android
cca v0.7.0
Running command: /home/lei/work/workspace/cordova/cordova-4.0/google_plugins/CIRC/hooks/before_prepare/cca-check.js /home/lei/work/workspace/cordova/cordova-4.0/google_plugins/CIRC
 Inject CSP for android
Running command: /home/lei/work/workspace/cordova/cordova-4.0/google_plugins/CIRC/platforms/android/cordova/run 
ANDROID_HOME=/home/lei/honry/adt-bundle-linux-x86-20140321/sdk
JAVA_HOME=/usr/lib/jvm/jdk1.6.0_34
WARNING : No target specified, deploying to device 'MedfieldCB1CBE92'.
Running: /home/lei/work/workspace/cordova/cordova-4.0/google_plugins/CIRC/platforms/android/gradlew cdvBuildDebug -b /home/lei/work/workspace/cordova/cordova-4.0/google_plugins/CIRC/platforms/android/build.gradle -PcdvBuildArch=x86 -Dorg.gradle.daemon=true
WARNING [Project: :] Current NDK support is deprecated.  Alternative will be provided in the future.
WARNING [Project: :] Current NDK support is deprecated.  Alternative will be provided in the future.
WARNING [Project: :] Current NDK support is deprecated.  Alternative will be provided in the future.
WARNING [Project: :] Current NDK support is deprecated.  Alternative will be provided in the future.
 
FAILURE: Build failed with an exception.
 
* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_armv7DebugCompile'.
   > Could not find any version that matches com.android.support:support-v4:+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/maven-metadata.xml
         https://repo1.maven.org/maven2/com/android/support/support-v4/
         https://download.01.org/crosswalk/releases/crosswalk/android/maven2/com/android/support/support-v4/maven-metadata.xml
         https://download.01.org/crosswalk/releases/crosswalk/android/maven2/com/android/support/support-v4/
     Required by:
         :android:unspecified
 
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
 
BUILD FAILED

**Comment by Honry** [comment]
Sorry, it is caused by I don't have the support repository downloaded into my android SDK.

Steps:
Open the SDK manager (from command line, type "android").
Under "Extras", Make sure you have "Android Support Repository" and "Google Repository" downloaded.

**Comment by iautomation** [comment]
This helped me with Cordova. Thankyou

**Comment by Urahara** [comment]
@Honry I had the same problem with Crosswalk and your answer solved my problem, thanks!

**Comment by fcazor1** [comment]
Thanks you Honry it solved my problem with Crosswalk.

**Comment by cyclops24** [comment]
I have same issue in meteor + crosswalk but I also install Android Support Repository" and "Google Repository" do you have any suggestion this is related issue:
https://github.com/meteor/meteor/issues/8135

**Comment by inexuscore** [comment]
I'm still struggling with this. I've used Crosswalk before in other projects but I can't seem to figure this out. I'm using Ionic 1.x and targetting android 16 to 24. I've installed maven/google/support repositories but I'm still getting the same error:

Could not resolve all dependencies for configuration ':_armv7DebugApkCopy'.
Could not find any matches for org.xwalk:xwalk_core_library_canary:17+ as no versions of org.xwalk:xwalk_core_library_canary are available.

I've tried crosswalk-lite and other versions, still no luck. 
This is really urgent I need to add crosswalk to my project. Could someone please answer this once and for all?
