### ISSUE TITLE
Ability to hide all join/quite/disconnected channel spam

### ISSUE THREAD

**Issue by Briksins** [flackr/circ#352]
Please add some option to tick or command to enter to ignore all spam from join leave users in channel
Its generated to much for big channels and it is hard read users messages between all this spam, even its different font style and color it is still too much robish which no need to display. 
In private chat it could be useful to notify that your opponent left but not in global chat

**Comment by cbandy** [comment]
See `/help ignore`

**Comment by Briksins** [comment]
ohh its native irc functionality... sorry about that! closing ticket!
