### ISSUE TITLE
Can't connect or irc.gitter.im

### ISSUE THREAD

**Issue by cauburtin** [flackr/circ#355]
![image](https://cloud.githubusercontent.com/assets/3134574/10963312/c239df7e-839f-11e5-83da-2c078d1d203b.png)

I tried putting (like they say here https://irc.gitter.im/) the /pass and /nick and /pass again, there seems to be a problem

circ supports ssl

**Comment by pierrebeaucamp** [comment]
Hi @cauburtin,

I could join irc.gitter.im with the following command:
````
/server irc.gitter.im +6667 yoursupersecrettoken
```` 

Where `yoursupersecrettoken` is your token / password.

Hope that helps.

**Comment by jcmdln** [comment]
I don't use gitter but was having a similar issue with freenode that is resolved using the connection method stated, though after signing up I was unable to connect to gitter which gave the following error:

```
Socket Error: tlsError: Could not parse certificate list.
```

**Comment by cauburtin** [comment]
thanks all

**Comment by pierrebeaucamp** [comment]
@jcmdln it seems that Gitter changed their SSL Certs on November 10. With the new Cert, issued by *Gandi Standard SSL CA 2*, CIRC will throw your error message.

Related Issues are #340 and maybe #338.
