### ISSUE TITLE
/ignore join part not working

### ISSUE THREAD

**Issue by cauburtin** [flackr/circ#356]
![image](https://cloud.githubusercontent.com/assets/3134574/10979485/180acb22-83fd-11e5-859e-cdb23943109c.png)

**Comment by tom-sherman** [comment]
Definitely related to issue #349

**Comment by fabioxgn** [comment]
@cauburtin use `/ignore join part quit` these messages in your screenshot are `quit` messages, not `part`.

**Comment by cauburtin** [comment]
thanks
