### ISSUE TITLE
Use a monospaced font

### ISSUE THREAD

**Issue by robbie0630** [flackr/circ#364]
Some servers have ASCII art that will only show in a monospaced font.

**Comment by flackr** [comment]
Hey, I think it's not likely to be made the default to use a monospaced font, but would it be sufficient for your case to load a theme which sets a monospaced font? For example, extract the attached zip and load it with the /theme command.
[monospaced.zip](https://github.com/flackr/circ/files/132581/monospaced.zip)

**Comment by robbie0630** [comment]
Huh, I didn't even notice it had a theming interface. Thanks for the tip :smiley_cat:
