### ISSUE TITLE
Doesn't support TLSv1.1 or TLSv1.2

### ISSUE THREAD

**Issue by fastcat** [flackr/circ#430]
TLSv1 and below are systematically being deprecated.  For example, Debian Buster will, by default, refuse to speak anything lower than TLSv1.2.

cIRC only supports TLSv1 it seems.

Much frustration ensued when I upgraded my znc host to said Debian release.

**Comment by flackr** [comment]
This has been resolved by 86db1a6c128fcabdeb561975e1c42e26e85ea86b.
